const assets = {
  images: {
    payment: "/images/payment.png",
    sales_manager: "/images/sales_manager.jpg",
    bg: {
      category_card: "/images/category-card-bg.png",
      login_bg: "/images/log-in-bg.png",
    },
    banners: {
      eggs: "/images/eggs-banner.jpg",
      fresh_fruits: "/images/fresh-fruits.jpg",
      fruits: "/images/fruits-banner.jpg",
      meats: "/images/meats-banner.jpg",
      nuts: "/images/nuts-banner.jpg",
      snacks: "/images/snacks-banner.jpg",
      vegetables: "/images/vegetable-banner.jpg",
      chicken: "/images/chicken.jpg",
      mushrooms: "/images/mushrooms.jpg",
      seafood: "/images/seafood.jpg",
      fresh_vegetable: "/images/fresh-vegetable.jpg",
      cashback: "/images/cashback.jpg",
      juice: "/images/juice.jpg",
      drinks: "/images/drinks.jpg",
      summer_vegetable: "/images/summer_vegetable.jpg",
      login: "/images/log-in.png",
    },
  },
  svg: {
    telephone: "/svg/Telephone.svg",
    love: "/svg/Love.svg",
    cart: "/svg/Cart.svg",
    bag: "/svg/Bag.svg",
    user: "/svg/User.svg",
    bars: "/svg/Bars.svg",
    products: "/svg/Products.svg",
    truck: "/svg/Truck.svg",
    discounts: "/svg/Discounts.svg",
    best_price: "/svg/BestPrice.svg",
    play_store: "/svg/PlayStore.svg",
    apple_store: "/svg/AppleStore.svg",
    hearth: "/svg/Heart.svg",
    magnifying_glass: "/svg/MagnifyingGlass.svg",
    leaf: "/svg/Leaf.svg",
  },
};

export default assets;
