services:  
- type: web   
 name: fast-mart-api   
 
 
 
  env: node    
  buildCommand: cd apps/api && npm install && npm run build    
  startCommand: cd apps/api && node render-server.js          
  envVars:     
   - key: NODE_ENV       
    value: production